# Rename this file to languages.toml to enable multilingual support

[fr]
languageName = "Français"
languagedirection = "ltr"
title = "lengel67-fr"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "lengel67-en"
weight = 2

[de]
languageName = "Deutsch"
languagedirection = "ltr"
title = "lengel67-de"
weight = 3
